services:
  - type: web
    name: lol-ai-backend
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: RIOT_API_KEY
        fromEnvVar: RIOT_API_KEY
      - key: REGION
        fromEnvVar: REGION
      - key: ROUTING
        fromEnvVar: ROUTING
